name: tarif_atlasi
description: "Türk mutfağından lezzetli tarifler."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  dotlottie_loader: ^0.0.4
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  provider: ^6.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo (1).webp
    - assets/images/fasulye.jpg
    - assets/images/pirinc.jpg
    - assets/images/pogaca.jpg
    - assets/images/salata.jpg
    - assets/images/patates.jpg
    - assets/images/mercimek.jpg
    - assets/images/domates.jpg
    - assets/images/yayla.jpg
    - assets/images/sütlac.jpg
    - assets/images/revani.jpg
    - assets/images/
    - assets/icons/
    - assets/languages/
    - assets/motions/